name: Convert PNG to WebP

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # ✅ use your PAT here

      - name: Set up ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Convert PNG to WebP
        run: |
          find assets/image -name "*.png" -exec bash -c 'cwebp "$0" -o "${0%.png}.webp"' {} \;

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # ✅ use your PAT here
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/image
          git diff --cached --quiet || git commit -m "Auto-convert images to WebP"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
