name: Convert images to WebP

on:
  push:
    branches:
      - main  # Runs when you push or update main branch

permissions:
  contents: write  # Allow the workflow to push commits

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository using your PAT (stored in GH_TOKEN)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      # 2️⃣ Install WebP utilities
      - name: Install WebP tools
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      # 3️⃣ Convert all .png / .jpg / .jpeg files to .webp (skips already existing .webp)
      - name: Convert images to WebP
        run: |
          find assets/image -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | while read img; do
            webp_path="${img%.*}.webp"
            if [ ! -f "$webp_path" ]; then
              echo "Converting: $img → $webp_path"
              cwebp -q 80 "$img" -o "$webp_path"
            fi
          done

      # 4️⃣ Commit and push converted files back to main branch
      - name: Commit and push converted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/image
          git diff --cached --quiet || git commit -m "Auto-convert images to WebP"
          git push

