name: Convert images to WebP

on:
  push:
    branches:
      - main
    paths:
      - 'assets/image/**.png'
      - 'assets/image/**.jpg'
      - 'assets/image/**.jpeg'
      - '.github/workflows/convert-images.yml'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # use your PAT here

      - name: Install WebP tools
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Convert PNG and JPG/JPEG to WebP
        run: |
          # Convert PNG files
          find assets/image -type f -name "*.png" -exec bash -c 'cwebp "$0" -o "${0%.png}.webp"' {} \;

          # Convert JPG files
          find assets/image -type f -name "*.jpg" -exec bash -c 'cwebp "$0" -o "${0%.jpg}.webp"' {} \;

          # Convert JPEG files
          find assets/image -type f -name "*.jpeg" -exec bash -c 'cwebp "$0" -o "${0%.jpeg}.webp"' {} \;

      - name: Commit and push WebP files
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/image
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-convert images (PNG + JPG) to WebP"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git main
          fi
