name: Convert images to WebP

on:
  push:
    branches: [ main ]
    paths:
      - "assets/image/**"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cwebp
        run: sudo apt-get install webp -y

      - name: Convert images to WebP
        run: |
          find assets/image -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" \) | while read img; do
            webp="${img%.*}.webp"
            cwebp -q 80 "$img" -o "$webp"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/image
          git diff --cached --quiet || git commit -m "Auto-convert images to WebP"
          git push
        env:
          TOKEN: ${{ secrets.TOKEN }}
